valid_email = 'romashkacool2003@gmail.com'
valid_phone = '+7(977)5612602'
valid_password = 'Hjvfirf2003'
valid_login = 'romashkacool2003'
valid_ls = '123456789098'
valid_username = u"Тестов Ромашка"
ad_slogan = u"Персональный помощник в цифровом мире Ростелекома"
site = 'https://b2c.passport.rt.ru'
link_lk = "/account_b2c/page"
drv_path = '../../ChromeDrv/chromedriver.exe'